# Generated by Django 3.2 on 2026-07-18 05:20

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_align_queued_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='operation',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='wallet',
            name='reserved_balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('reservation', 'Reservation'), ('reservation_release', 'Reservation release'), ('withdrawal', 'Withdrawal')], max_length=24),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='withdrawal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='wallets.withdrawal'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('queued', 'Queued'), ('processing', 'Processing'), ('funds_reserved', 'Funds reserved'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('insufficient_funds', 'Insufficient funds')], default='scheduled', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('withdrawal', 'operation'), name='unique_withdrawal_ledger_operation'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(reserved_balance__gte=0), name='wallet_reserved_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(reserved_balance__lte=django.db.models.expressions.F('balance')), name='wallet_reserved_within_balance'),
        ),
    ]
