# Generated by Django 3.2 on 2026-07-18 05:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_auto_20260718_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='last_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='last_failure_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='last_failure_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('queued', 'Queued'), ('processing', 'Processing'), ('funds_reserved', 'Funds reserved'), ('retry_pending', 'Retry pending'), ('reconciliation_required', 'Reconciliation required'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('insufficient_funds', 'Insufficient funds')], default='scheduled', max_length=24),
        ),
        migrations.CreateModel(
            name='BankTransferAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('idempotency_key', models.UUIDField()),
                ('outcome', models.CharField(max_length=32)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('bank_reference', models.CharField(blank=True, max_length=128)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_attempts', to='wallets.withdrawal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='banktransferattempt',
            constraint=models.UniqueConstraint(fields=('withdrawal', 'attempt_number'), name='unique_bank_attempt_number'),
        ),
    ]
