# Generated by Django 3.2 on 2026-07-18 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_auto_20260718_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiIdempotency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('operation', models.CharField(max_length=32)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(default='process_withdrawal', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('withdrawal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='wallets.withdrawal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='apiidempotency',
            constraint=models.UniqueConstraint(fields=('key', 'operation'), name='unique_api_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['published_at', 'next_attempt_at'], name='wallets_out_publish_0df047_idx'),
        ),
    ]
